# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/I2C_FIFO/I2C_FIFO.xci
# IP: The module: 'I2C_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/I2C_FIFO/I2C_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_FIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/I2C_FIFO/I2C_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/I2C_FIFO/I2C_FIFO.xci
# IP: The module: 'I2C_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/I2C_FIFO/I2C_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/I2C_FIFO/I2C_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
