# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/ADC_CONFIG_ILA/ADC_CONFIG_ILA.xci
# IP: The module: 'ADC_CONFIG_ILA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_CONFIG_ILA'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_CONFIG_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ADC_CONFIG_ILA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_CONFIG_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/ADC_CONFIG_ILA/ADC_CONFIG_ILA.xci
# IP: The module: 'ADC_CONFIG_ILA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_CONFIG_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_CONFIG_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ADC_CONFIG_ILA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_CONFIG_ILA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
