@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Jul 01 16:56:23 +0100 2025
REM SW Build 6060944 on Thu Mar 06 19:10:01 MST 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 16 -L xil_defaultlib -L fifo_generator_v13_2_12 -L lib_pkg_v1_0_4 -L lib_cdc_v1_0_3 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_5 -L axi_iic_v2_1_10 -L gigantic_mux -L xlconcat_v2_1_6 -L axis_infrastructure_v1_1_1 -L axis_register_slice_v1_1_34 -L axis_dwidth_converter_v1_1_33 -L xbip_utils_v3_0_14 -L mult_gen_v12_0_22 -L tri_mode_ethernet_mac_v9_0_37 -L axis_data_fifo_v2_0_16 -L util_vector_logic_v2_0_4 -L proc_sys_reset_v5_0_16 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot UDP_PACKAGE_tb_behav xil_defaultlib.UDP_PACKAGE_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 16 -L xil_defaultlib -L fifo_generator_v13_2_12 -L lib_pkg_v1_0_4 -L lib_cdc_v1_0_3 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_5 -L axi_iic_v2_1_10 -L gigantic_mux -L xlconcat_v2_1_6 -L axis_infrastructure_v1_1_1 -L axis_register_slice_v1_1_34 -L axis_dwidth_converter_v1_1_33 -L xbip_utils_v3_0_14 -L mult_gen_v12_0_22 -L tri_mode_ethernet_mac_v9_0_37 -L axis_data_fifo_v2_0_16 -L util_vector_logic_v2_0_4 -L proc_sys_reset_v5_0_16 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot UDP_PACKAGE_tb_behav xil_defaultlib.UDP_PACKAGE_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
