# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/axis_eth_head_convertor/axis_eth_head_convertor.xci
# IP: The module: 'axis_eth_head_convertor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/axis_eth_head_convertor/axis_eth_head_convertor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_eth_head_convertor'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/axis_eth_head_convertor/axis_eth_head_convertor.xci
# IP: The module: 'axis_eth_head_convertor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/axis_eth_head_convertor/axis_eth_head_convertor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_eth_head_convertor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
