# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit.xci
# IP: The module: 'spi_rx_fifo_16bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_rx_fifo_16bit'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_rx_fifo_16bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit.xci
# IP: The module: 'spi_rx_fifo_16bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_rx_fifo_16bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_rx_fifo_16bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
