# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/DDR4/ip/DDR4_dpuczdx8g_0_0/DDR4_dpuczdx8g_0_0.xci
# IP: The module: 'DDR4_dpuczdx8g_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_dpuczdx8g_0_0/DDR4_dpuczdx8g_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_dpuczdx8g_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_dpuczdx8g_0_0/DDR4_dpuczdx8g_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_dpuczdx8g_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/DDR4/ip/DDR4_dpuczdx8g_0_0/DDR4_dpuczdx8g_0_0.xci
# IP: The module: 'DDR4_dpuczdx8g_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_dpuczdx8g_0_0/DDR4_dpuczdx8g_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_dpuczdx8g_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_dpuczdx8g_0_0/DDR4_dpuczdx8g_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_dpuczdx8g_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
