# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/DDR4_ddr4_0_0.xci
# IP: The module: 'DDR4_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_1/DDR4_ddr4_0_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_ddr4_0_0_phy || ORIG_REF_NAME==DDR4_ddr4_0_0_phy} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_0/DDR4_ddr4_0_0_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==DDR4_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/bd_cfe9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9 || ORIG_REF_NAME==bd_cfe9} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_0/bd_cfe9_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_microblaze_I_0 || ORIG_REF_NAME==bd_cfe9_microblaze_I_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_1/bd_cfe9_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_rst_0_0 || ORIG_REF_NAME==bd_cfe9_rst_0_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_2/bd_cfe9_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_ilmb_0 || ORIG_REF_NAME==bd_cfe9_ilmb_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_3/bd_cfe9_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_dlmb_0 || ORIG_REF_NAME==bd_cfe9_dlmb_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_4/bd_cfe9_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_dlmb_cntlr_0 || ORIG_REF_NAME==bd_cfe9_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_5/bd_cfe9_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_ilmb_cntlr_0 || ORIG_REF_NAME==bd_cfe9_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_6/bd_cfe9_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_lmb_bram_I_0 || ORIG_REF_NAME==bd_cfe9_lmb_bram_I_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_7/bd_cfe9_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_cfe9_second_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_8/bd_cfe9_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_cfe9_second_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_9/bd_cfe9_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_cfe9_second_lmb_bram_I_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_10/bd_cfe9_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_iomodule_0_0 || ORIG_REF_NAME==bd_cfe9_iomodule_0_0} -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_1/par/DDR4_ddr4_0_0_phy_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_0/bd_cfe9_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_microblaze_I_0 || ORIG_REF_NAME==bd_cfe9_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_0/bd_cfe9_microblaze_I_0_ooc_debug.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_1/bd_cfe9_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_rst_0_0 || ORIG_REF_NAME==bd_cfe9_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_1/bd_cfe9_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_rst_0_0 || ORIG_REF_NAME==bd_cfe9_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_2/bd_cfe9_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_ilmb_0 || ORIG_REF_NAME==bd_cfe9_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_3/bd_cfe9_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_dlmb_0 || ORIG_REF_NAME==bd_cfe9_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_6/bd_cfe9_lmb_bram_I_0_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_9/bd_cfe9_second_lmb_bram_I_0_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_10/bd_cfe9_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_iomodule_0_0 || ORIG_REF_NAME==bd_cfe9_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/bd_cfe9_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_0/DDR4_ddr4_0_0_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR4_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==DDR4_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_0/DDR4_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/DDR4_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/par/DDR4_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/DDR4_ddr4_0_0.xci
# IP: The module: 'DDR4_ddr4_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_1/DDR4_ddr4_0_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_ddr4_0_0_phy || ORIG_REF_NAME==DDR4_ddr4_0_0_phy} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_0/DDR4_ddr4_0_0_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==DDR4_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/bd_cfe9.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9 || ORIG_REF_NAME==bd_cfe9} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_0/bd_cfe9_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_microblaze_I_0 || ORIG_REF_NAME==bd_cfe9_microblaze_I_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_1/bd_cfe9_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_rst_0_0 || ORIG_REF_NAME==bd_cfe9_rst_0_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_2/bd_cfe9_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_ilmb_0 || ORIG_REF_NAME==bd_cfe9_ilmb_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_3/bd_cfe9_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_dlmb_0 || ORIG_REF_NAME==bd_cfe9_dlmb_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_4/bd_cfe9_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_dlmb_cntlr_0 || ORIG_REF_NAME==bd_cfe9_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_5/bd_cfe9_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_ilmb_cntlr_0 || ORIG_REF_NAME==bd_cfe9_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_6/bd_cfe9_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_lmb_bram_I_0 || ORIG_REF_NAME==bd_cfe9_lmb_bram_I_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_7/bd_cfe9_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_cfe9_second_dlmb_cntlr_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_8/bd_cfe9_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_cfe9_second_ilmb_cntlr_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_9/bd_cfe9_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_cfe9_second_lmb_bram_I_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_10/bd_cfe9_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_cfe9_iomodule_0_0 || ORIG_REF_NAME==bd_cfe9_iomodule_0_0} -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_1/par/DDR4_ddr4_0_0_phy_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_0/bd_cfe9_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_microblaze_I_0 || ORIG_REF_NAME==bd_cfe9_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_0/bd_cfe9_microblaze_I_0_ooc_debug.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_1/bd_cfe9_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_rst_0_0 || ORIG_REF_NAME==bd_cfe9_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_1/bd_cfe9_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_rst_0_0 || ORIG_REF_NAME==bd_cfe9_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_2/bd_cfe9_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_ilmb_0 || ORIG_REF_NAME==bd_cfe9_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_3/bd_cfe9_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_dlmb_0 || ORIG_REF_NAME==bd_cfe9_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_6/bd_cfe9_lmb_bram_I_0_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_9/bd_cfe9_second_lmb_bram_I_0_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/ip/ip_10/bd_cfe9_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cfe9_iomodule_0_0 || ORIG_REF_NAME==bd_cfe9_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/bd_0/bd_cfe9_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_0/DDR4_ddr4_0_0_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR4_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==DDR4_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/ip_0/DDR4_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/DDR4_ddr4_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_ddr4_0_0/par/DDR4_ddr4_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_ddr4_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
