# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/data_to_udp_fifo/data_to_udp_fifo.xci
# IP: The module: 'data_to_udp_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/data_to_udp_fifo/data_to_udp_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_to_udp_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/data_to_udp_fifo/data_to_udp_fifo.xci
# IP: The module: 'data_to_udp_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/data_to_udp_fifo/data_to_udp_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_to_udp_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
