# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/AD7606.xdc

# XDC: new/ICM42688.xdc

# XDC: new/MAX86916.xdc

# XDC: new/ETH_PHY.xdc

# XDC: new/BITSTREAM.xdc

# IP: ip/IMU_TOP_VIO/IMU_TOP_VIO.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IMU_TOP_VIO || ORIG_REF_NAME==IMU_TOP_VIO} -quiet] -quiet

# Block Designs: bd/PPG_I2C_PHY/PPG_I2C_PHY.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY || ORIG_REF_NAME==PPG_I2C_PHY} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_axi_iic_0_0/PPG_I2C_PHY_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_axi_iic_0_0 || ORIG_REF_NAME==PPG_I2C_PHY_axi_iic_0_0} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_util_ds_buf_0_0/PPG_I2C_PHY_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_util_ds_buf_0_0 || ORIG_REF_NAME==PPG_I2C_PHY_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_util_ds_buf_0_1/PPG_I2C_PHY_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_util_ds_buf_0_1 || ORIG_REF_NAME==PPG_I2C_PHY_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_ila_0_0/PPG_I2C_PHY_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_ila_0_0 || ORIG_REF_NAME==PPG_I2C_PHY_ila_0_0} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_system_ila_0_0/PPG_I2C_PHY_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_system_ila_0_0 || ORIG_REF_NAME==PPG_I2C_PHY_system_ila_0_0} -quiet] -quiet

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# Block Designs: bd/RGMII/RGMII.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII || ORIG_REF_NAME==RGMII} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_tri_mode_ethernet_mac_0_0/RGMII_tri_mode_ethernet_mac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_tri_mode_ethernet_mac_0_0 || ORIG_REF_NAME==RGMII_tri_mode_ethernet_mac_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_axis_TX_data_fifo_0/RGMII_axis_TX_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_axis_TX_data_fifo_0 || ORIG_REF_NAME==RGMII_axis_TX_data_fifo_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_util_vector_logic_0_0/RGMII_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_util_vector_logic_0_0 || ORIG_REF_NAME==RGMII_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_util_vector_logic_0_1/RGMII_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_util_vector_logic_0_1 || ORIG_REF_NAME==RGMII_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_system_ila_0_0/RGMII_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_system_ila_0_0 || ORIG_REF_NAME==RGMII_system_ila_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_vio_0_0/RGMII_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_vio_0_0 || ORIG_REF_NAME==RGMII_vio_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_axis_data_fifo_0_0/RGMII_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_axis_data_fifo_0_0 || ORIG_REF_NAME==RGMII_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_rst_TEMAC_125M_0/RGMII_rst_TEMAC_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_rst_TEMAC_125M_0 || ORIG_REF_NAME==RGMII_rst_TEMAC_125M_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_system_ila_1_0/RGMII_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_system_ila_1_0 || ORIG_REF_NAME==RGMII_system_ila_1_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_system_ila_0_1/RGMII_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_system_ila_0_1 || ORIG_REF_NAME==RGMII_system_ila_0_1} -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/PPG_I2C_PHY_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/RGMII_ooc.xdc
