# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/DDR4.xdc

# XDC: new/AD7606.xdc

# XDC: new/ICM42688.xdc

# XDC: new/ETH_PHY.xdc

# XDC: new/BITSTREAM.xdc

# XDC: new/TIME_CONSTRS.xdc

# Block Designs: bd/PPG_I2C_PHY/PPG_I2C_PHY.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY || ORIG_REF_NAME==PPG_I2C_PHY} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_axi_iic_0_0/PPG_I2C_PHY_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_axi_iic_0_0 || ORIG_REF_NAME==PPG_I2C_PHY_axi_iic_0_0} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_util_ds_buf_0_0/PPG_I2C_PHY_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_util_ds_buf_0_0 || ORIG_REF_NAME==PPG_I2C_PHY_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_util_ds_buf_0_1/PPG_I2C_PHY_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_util_ds_buf_0_1 || ORIG_REF_NAME==PPG_I2C_PHY_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_ila_0_0/PPG_I2C_PHY_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_ila_0_0 || ORIG_REF_NAME==PPG_I2C_PHY_ila_0_0} -quiet] -quiet

# IP: bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_system_ila_0_0/PPG_I2C_PHY_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PPG_I2C_PHY_system_ila_0_0 || ORIG_REF_NAME==PPG_I2C_PHY_system_ila_0_0} -quiet] -quiet

# Block Designs: bd/RGMII/RGMII.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII || ORIG_REF_NAME==RGMII} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_tri_mode_ethernet_mac_0_0/RGMII_tri_mode_ethernet_mac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_tri_mode_ethernet_mac_0_0 || ORIG_REF_NAME==RGMII_tri_mode_ethernet_mac_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_util_vector_logic_0_0/RGMII_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_util_vector_logic_0_0 || ORIG_REF_NAME==RGMII_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_util_vector_logic_0_1/RGMII_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_util_vector_logic_0_1 || ORIG_REF_NAME==RGMII_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_vio_0_0/RGMII_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_vio_0_0 || ORIG_REF_NAME==RGMII_vio_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_axis_data_fifo_0_0/RGMII_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_axis_data_fifo_0_0 || ORIG_REF_NAME==RGMII_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_system_ila_1_0/RGMII_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_system_ila_1_0 || ORIG_REF_NAME==RGMII_system_ila_1_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_system_ila_0_2/RGMII_system_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_system_ila_0_2 || ORIG_REF_NAME==RGMII_system_ila_0_2} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_axis_TX_data_fifo_0/RGMII_axis_TX_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_axis_TX_data_fifo_0 || ORIG_REF_NAME==RGMII_axis_TX_data_fifo_0} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_system_ila_0_3/RGMII_system_ila_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_system_ila_0_3 || ORIG_REF_NAME==RGMII_system_ila_0_3} -quiet] -quiet

# IP: bd/RGMII/ip/RGMII_system_ila_TX_0/RGMII_system_ila_TX_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RGMII_system_ila_TX_0 || ORIG_REF_NAME==RGMII_system_ila_TX_0} -quiet] -quiet

# Block Designs: bd/DDR4/DDR4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4 || ORIG_REF_NAME==DDR4} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_ddr4_0_0/DDR4_ddr4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_ddr4_0_0 || ORIG_REF_NAME==DDR4_ddr4_0_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_util_vector_logic_0_0/DDR4_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_util_vector_logic_0_0 || ORIG_REF_NAME==DDR4_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_util_vector_logic_1_0/DDR4_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_util_vector_logic_1_0 || ORIG_REF_NAME==DDR4_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_proc_sys_reset_0_0/DDR4_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_proc_sys_reset_0_0 || ORIG_REF_NAME==DDR4_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_zynq_ultra_ps_e_0_1/DDR4_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==DDR4_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_xbar_0/DDR4_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s00_data_fifo_0/DDR4_axi_interconnect_0_imp_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_s00_data_fifo_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_s00_data_fifo_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_auto_cc_0/DDR4_axi_interconnect_0_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_auto_cc_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_auto_cc_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s01_data_fifo_0/DDR4_axi_interconnect_0_imp_s01_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_s01_data_fifo_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_s01_data_fifo_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_auto_cc_1/DDR4_axi_interconnect_0_imp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_auto_cc_1 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_auto_cc_1} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s02_data_fifo_0/DDR4_axi_interconnect_0_imp_s02_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_s02_data_fifo_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_s02_data_fifo_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_auto_cc_2/DDR4_axi_interconnect_0_imp_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_auto_cc_2 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_auto_cc_2} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s03_data_fifo_0/DDR4_axi_interconnect_0_imp_s03_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_s03_data_fifo_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_s03_data_fifo_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_auto_cc_3/DDR4_axi_interconnect_0_imp_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_auto_cc_3 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_auto_cc_3} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s00_mmu_0/DDR4_axi_interconnect_0_imp_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_s00_mmu_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_s00_mmu_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s01_mmu_0/DDR4_axi_interconnect_0_imp_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_s01_mmu_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_s01_mmu_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s02_mmu_0/DDR4_axi_interconnect_0_imp_s02_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_imp_s02_mmu_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_imp_s02_mmu_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_axi_interconnect_0_0/DDR4_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_axi_interconnect_0_0 || ORIG_REF_NAME==DDR4_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_dpuczdx8g_0_0/DDR4_dpuczdx8g_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_dpuczdx8g_0_0 || ORIG_REF_NAME==DDR4_dpuczdx8g_0_0} -quiet] -quiet

# IP: bd/DDR4/ip/DDR4_proc_sys_reset_0_1/DDR4_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR4_proc_sys_reset_0_1 || ORIG_REF_NAME==DDR4_proc_sys_reset_0_1} -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/PPG_I2C_PHY_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/RGMII_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/DDR4_ooc.xdc
