# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/final_prj/final_prj_pl/final_prj_pl.runs/synth_1/TOP.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param general.maxThreads 16
set_param chipscope.maxJobs 8
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param xicom.use_bs_reader 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/final_prj/final_prj_pl/final_prj_pl.cache/wt [current_project]
set_property parent.project_path E:/final_prj/final_prj_pl/final_prj_pl.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/final_prj/final_prj_pl/final_prj_pl.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/ADC_CONFIG.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/ADC_TOP.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/ADC_SPI_PHY.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/ADC_SPI_LINK.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/ADC_READ.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/IMU_SPI_PHY.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/IMU_SPI_LINK.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/IMU_TOP.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/IMU_CONFIG.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/IMU_READ.v
  E:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/hdl/PPG_I2C_PHY_wrapper.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/I2C_TOP.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/I2C_RW_CTRL.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/I2C_CONFIG_READ.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/SENSOR_TOP.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/TOP.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/UDP_PACKAGE.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/UDP_CONFIG.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/axi4lite_process.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/UDP_TOP.v
  E:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/hdl/RGMII_wrapper.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/DATA_PROCESS_TOP.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/DATA_ORDER.v
  E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/new/DATA_TO_UDP.v
}
read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/IMU_TOP_VIO/IMU_TOP_VIO.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/IMU_TOP_VIO/IMU_TOP_VIO.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/IMU_TOP_VIO/IMU_TOP_VIO_ooc.xdc]

add_files E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/PPG_I2C_PHY/PPG_I2C_PHY.bd
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_axi_iic_0_0/PPG_I2C_PHY_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_axi_iic_0_0/PPG_I2C_PHY_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_util_ds_buf_0_0/PPG_I2C_PHY_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_util_ds_buf_0_0/PPG_I2C_PHY_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_util_ds_buf_0_1/PPG_I2C_PHY_util_ds_buf_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_util_ds_buf_0_1/PPG_I2C_PHY_util_ds_buf_0_1_board.xdc]
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_ila_0_0/PPG_I2C_PHY_ila_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_system_ila_0_0/bd_0/ip/ip_0/bd_d1f0_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_system_ila_0_0/bd_0/bd_d1f0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/ip/PPG_I2C_PHY_system_ila_0_0/PPG_I2C_PHY_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/PPG_I2C_PHY/PPG_I2C_PHY_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

add_files E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/RGMII/RGMII.bd
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_tri_mode_ethernet_mac_0_0/synth/RGMII_tri_mode_ethernet_mac_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_tri_mode_ethernet_mac_0_0/synth/RGMII_tri_mode_ethernet_mac_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_tri_mode_ethernet_mac_0_0/synth/RGMII_tri_mode_ethernet_mac_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_tri_mode_ethernet_mac_0_0/synth/RGMII_tri_mode_ethernet_mac_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_axis_TX_data_fifo_0/RGMII_axis_TX_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_0/bd_0/ip/ip_0/bd_bb77_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_0/bd_0/bd_bb77_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_0/RGMII_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_vio_0_0/RGMII_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_vio_0_0/RGMII_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_axis_data_fifo_0_0/RGMII_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_rst_TEMAC_125M_0/RGMII_rst_TEMAC_125M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_rst_TEMAC_125M_0/RGMII_rst_TEMAC_125M_0.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_rst_TEMAC_125M_0/RGMII_rst_TEMAC_125M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_1_0/bd_0/ip/ip_0/bd_7b26_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_1_0/bd_0/bd_7b26_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_1_0/RGMII_system_ila_1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_1/bd_0/ip/ip_0/bd_7bb6_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_1/bd_0/bd_7bb6_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_0_1/RGMII_system_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/RGMII_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/ila_2/ila_2.xci
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ila_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ila_2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ila_2/ila_2_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/spi_tx_fifo/spi_tx_fifo.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_tx_fifo/spi_tx_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_tx_fifo/spi_tx_fifo_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/spi_rx_fifo/spi_rx_fifo.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_rx_fifo/spi_rx_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_rx_fifo/spi_rx_fifo_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/ADC_CONFIG_ILA/ADC_CONFIG_ILA.xci
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_CONFIG_ILA/ADC_CONFIG_ILA_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/ADC_TOP_VIO/ADC_TOP_VIO.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_TOP_VIO/ADC_TOP_VIO.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_TOP_VIO/ADC_TOP_VIO_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/ADC_READ_ILA/ADC_READ_ILA.xci
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_READ_ILA/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_READ_ILA/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_READ_ILA/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/ADC_READ_ILA/ADC_READ_ILA_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/spi_rx_fifo_16bit/spi_rx_fifo_16bit_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/IMU_test_vio/IMU_test_vio.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/IMU_test_vio/IMU_test_vio.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/IMU_test_vio/IMU_test_vio_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/imu_read_ila/imu_read_ila.xci
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/imu_read_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/imu_read_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/imu_read_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/imu_read_ila/imu_read_ila_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/IMU_CONFIG_ILA/IMU_CONFIG_ILA.xci
set_property used_in_synthesis false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/IMU_CONFIG_ILA/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/IMU_CONFIG_ILA/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/IMU_CONFIG_ILA/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/IMU_CONFIG_ILA/IMU_CONFIG_ILA_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/udp_config_vio/udp_config_vio.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/udp_config_vio/udp_config_vio.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/udp_config_vio/udp_config_vio_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/axis_eth_head_convertor/axis_eth_head_convertor.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/axis_eth_head_convertor/axis_eth_head_convertor_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/system_clock/system_clock.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_board.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_late.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/top_vio/top_vio.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/top_vio/top_vio.xdc]
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/top_vio/top_vio_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/data_to_udp_fifo/data_to_udp_fifo.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/data_to_udp_fifo/data_to_udp_fifo_ooc.xdc]

read_ip -quiet E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/data_to_udp_fifo_widcov/data_to_udp_fifo_widcov.xci
set_property used_in_implementation false [get_files -all e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/data_to_udp_fifo_widcov/data_to_udp_fifo_widcov_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/AD7606.xdc
set_property used_in_implementation false [get_files E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/AD7606.xdc]

read_xdc E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/ICM42688.xdc
set_property used_in_implementation false [get_files E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/ICM42688.xdc]

read_xdc E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/MAX86916.xdc
set_property used_in_implementation false [get_files E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/MAX86916.xdc]

read_xdc E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/ETH_PHY.xdc
set_property used_in_implementation false [get_files E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/ETH_PHY.xdc]

read_xdc E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/BITSTREAM.xdc
set_property used_in_implementation false [get_files E:/final_prj/final_prj_pl/final_prj_pl.srcs/constrs_1/new/BITSTREAM.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/final_prj/final_prj_pl/final_prj_pl.srcs/utils_1/imports/synth_1/ADC_TOP_test.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top TOP -part xczu9eg-ffvb1156-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
