# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s00_mmu_0/DDR4_axi_interconnect_0_imp_s00_mmu_0.xci
# IP: The module: 'DDR4_axi_interconnect_0_imp_s00_mmu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s00_mmu_0/DDR4_axi_interconnect_0_imp_s00_mmu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_axi_interconnect_0_imp_s00_mmu_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s00_mmu_0/DDR4_axi_interconnect_0_imp_s00_mmu_0.xci
# IP: The module: 'DDR4_axi_interconnect_0_imp_s00_mmu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/DDR4/ip/DDR4_axi_interconnect_0_imp_s00_mmu_0/DDR4_axi_interconnect_0_imp_s00_mmu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDR4_axi_interconnect_0_imp_s00_mmu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
