# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/system_clock/system_clock.xci
# IP: The module: 'system_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/ip/system_clock/system_clock.xci
# IP: The module: 'system_clock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/ip/system_clock/system_clock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
