-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2.2 (win64) Build 6060944 Thu Mar 06 19:10:01 MST 2025
-- Date        : Mon Jul 28 14:19:14 2025
-- Host        : LAPTOP-VEGJAO5A running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ DDR4_dpuczdx8g_0_0_stub.vhdl
-- Design      : DDR4_dpuczdx8g_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu9eg-ffvb1156-2-i
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    dpu_2x_clk : in STD_LOGIC;
    dpu_2x_resetn : in STD_LOGIC;
    m_axi_dpu_aclk : in STD_LOGIC;
    m_axi_dpu_aresetn : in STD_LOGIC;
    dpu0_interrupt : out STD_LOGIC;
    s_axi_awid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s_axi_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_awlock : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_awcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_awqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_awregion : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_awuser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_awvalid : in STD_LOGIC;
    s_axi_awready : out STD_LOGIC;
    s_axi_wid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_wlast : in STD_LOGIC;
    s_axi_wvalid : in STD_LOGIC;
    s_axi_wready : out STD_LOGIC;
    s_axi_bid : out STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_bvalid : out STD_LOGIC;
    s_axi_bready : in STD_LOGIC;
    s_axi_arid : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    s_axi_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_arlock : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_arcache : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_arqos : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_arregion : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_aruser : in STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_arvalid : in STD_LOGIC;
    s_axi_arready : out STD_LOGIC;
    s_axi_rid : out STD_LOGIC_VECTOR ( 15 downto 0 );
    s_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_rlast : out STD_LOGIC;
    s_axi_rvalid : out STD_LOGIC;
    s_axi_rready : in STD_LOGIC;
    dpu0_m_axi_instr_awid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_instr_awaddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    dpu0_m_axi_instr_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    dpu0_m_axi_instr_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_instr_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_instr_awlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_instr_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_instr_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_instr_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_instr_awuser : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_instr_awvalid : out STD_LOGIC;
    dpu0_m_axi_instr_awready : in STD_LOGIC;
    dpu0_m_axi_instr_wid : out STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_instr_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    dpu0_m_axi_instr_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_instr_wlast : out STD_LOGIC;
    dpu0_m_axi_instr_wvalid : out STD_LOGIC;
    dpu0_m_axi_instr_wready : in STD_LOGIC;
    dpu0_m_axi_instr_bid : in STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_instr_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_instr_bvalid : in STD_LOGIC;
    dpu0_m_axi_instr_bready : out STD_LOGIC;
    dpu0_m_axi_instr_arid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_instr_araddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    dpu0_m_axi_instr_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    dpu0_m_axi_instr_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_instr_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_instr_arlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_instr_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_instr_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_instr_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_instr_aruser : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_instr_arvalid : out STD_LOGIC;
    dpu0_m_axi_instr_arready : in STD_LOGIC;
    dpu0_m_axi_instr_rid : in STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_instr_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    dpu0_m_axi_instr_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_instr_rlast : in STD_LOGIC;
    dpu0_m_axi_instr_rvalid : in STD_LOGIC;
    dpu0_m_axi_instr_rready : out STD_LOGIC;
    dpu0_m_axi_data0_awid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data0_awaddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    dpu0_m_axi_data0_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    dpu0_m_axi_data0_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_data0_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data0_awlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_data0_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_data0_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_data0_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_data0_awuser : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_data0_awvalid : out STD_LOGIC;
    dpu0_m_axi_data0_awready : in STD_LOGIC;
    dpu0_m_axi_data0_wid : out STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_data0_wdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    dpu0_m_axi_data0_wstrb : out STD_LOGIC_VECTOR ( 15 downto 0 );
    dpu0_m_axi_data0_wlast : out STD_LOGIC;
    dpu0_m_axi_data0_wvalid : out STD_LOGIC;
    dpu0_m_axi_data0_wready : in STD_LOGIC;
    dpu0_m_axi_data0_bid : in STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_data0_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data0_bvalid : in STD_LOGIC;
    dpu0_m_axi_data0_bready : out STD_LOGIC;
    dpu0_m_axi_data0_arid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data0_araddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    dpu0_m_axi_data0_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    dpu0_m_axi_data0_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_data0_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data0_arlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_data0_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_data0_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_data0_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_data0_aruser : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_data0_arvalid : out STD_LOGIC;
    dpu0_m_axi_data0_arready : in STD_LOGIC;
    dpu0_m_axi_data0_rid : in STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_data0_rdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    dpu0_m_axi_data0_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data0_rlast : in STD_LOGIC;
    dpu0_m_axi_data0_rvalid : in STD_LOGIC;
    dpu0_m_axi_data0_rready : out STD_LOGIC;
    dpu0_m_axi_data1_awid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data1_awaddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    dpu0_m_axi_data1_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    dpu0_m_axi_data1_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_data1_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data1_awlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_data1_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_data1_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_data1_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_data1_awuser : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_data1_awvalid : out STD_LOGIC;
    dpu0_m_axi_data1_awready : in STD_LOGIC;
    dpu0_m_axi_data1_wid : out STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_data1_wdata : out STD_LOGIC_VECTOR ( 127 downto 0 );
    dpu0_m_axi_data1_wstrb : out STD_LOGIC_VECTOR ( 15 downto 0 );
    dpu0_m_axi_data1_wlast : out STD_LOGIC;
    dpu0_m_axi_data1_wvalid : out STD_LOGIC;
    dpu0_m_axi_data1_wready : in STD_LOGIC;
    dpu0_m_axi_data1_bid : in STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_data1_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data1_bvalid : in STD_LOGIC;
    dpu0_m_axi_data1_bready : out STD_LOGIC;
    dpu0_m_axi_data1_arid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data1_araddr : out STD_LOGIC_VECTOR ( 39 downto 0 );
    dpu0_m_axi_data1_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    dpu0_m_axi_data1_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_data1_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data1_arlock : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_data1_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_data1_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    dpu0_m_axi_data1_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    dpu0_m_axi_data1_aruser : out STD_LOGIC_VECTOR ( 0 to 0 );
    dpu0_m_axi_data1_arvalid : out STD_LOGIC;
    dpu0_m_axi_data1_arready : in STD_LOGIC;
    dpu0_m_axi_data1_rid : in STD_LOGIC_VECTOR ( 5 downto 0 );
    dpu0_m_axi_data1_rdata : in STD_LOGIC_VECTOR ( 127 downto 0 );
    dpu0_m_axi_data1_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    dpu0_m_axi_data1_rlast : in STD_LOGIC;
    dpu0_m_axi_data1_rvalid : in STD_LOGIC;
    dpu0_m_axi_data1_rready : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "DDR4_dpuczdx8g_0_0,DPUCZDX8G_v4_1_0,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "DDR4_dpuczdx8g_0_0,DPUCZDX8G_v4_1_0,{x_ipProduct=Vivado 2024.2.2,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=dpuczdx8g,x_ipVersion=4.1,x_ipCoreRevision=0,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,VER_CHIP_PART=3,VER_DPU_NUM=1,CLK_GATING_ENA=0,DSP48_VER=DSP48E2,S_AXI_FREQ_MHZ=97,S_AXI_CLK_INDEPENDENT=0,S_AXI_SLAVES_BASE_ADDR=0x81000000,S_AXI_ID_BW=16,S_AXI_AWRLEN_BW=8,M_AXI_FREQ_MHZ=97,M_AXI_AWRLEN_BW=8,M_AXI_AWRUSER_BW=1,M_AXI_AWRLOCK_BW=1,GP_ID_BW=2,HP0_ID_BW=2,HP1_ID_BW=2,HP2_ID_BW=2,HP3_ID_BW=2,HP_DATA_BW=128,SYS_IP_VER=0x41,SYS_IP_TYPE=1,SYS_REGMAP_SIZE=12,SYS_REGMAP_VER=0x01,TIME_YEAR=25,TIME_MONTH=7,TIME_DAY=28,TIME_HOUR=11,TIME_QUARTER=1,GIT_COMMIT_ID=0x07d32c41,GIT_COMMIT_TIME=2023022121,VER_IP_REV=0x00,VER_TARGET=0x141,ARCH_HP_BW=3,ARCH_DATA_BW=1,ARCH_IMG_BKGRP=3,ARCH_PP=8,ARCH_ICP=16,ARCH_OCP=16,RAM_DEPTH_MEAN=1,RAM_DEPTH_BIAS=3,RAM_DEPTH_WGT=3,RAM_DEPTH_IMG=3,UBANK_IMG_N=0,UBANK_WGT_N=0,UBANK_BIAS=0,DBANK_IMG_N=0,DBANK_WGT_N=0,DBANK_BIAS=0,LOAD_AUGM=1,LOAD_IMG_MEAN=0,LOAD_PARALLEL=2,CONV_LEAKYRELU=1,CONV_RELU6=1,CONV_WR_PARALLEL=1,CONV_DSP_CASC_MAX=4,CONV_DSP_ACCU_ENA=1,SAVE_PARALLEL=2,SAVE_ARGMAX_ENA=1,POOL_AVERAGE=1,ELEW_PARALLEL=8,ELEW_MULT_EN=1,ALU_LEAKYRELU=0,ALU_PARALLEL=8,MISC_WR_PARALLEL=1,DNNDK_PRINT=Number of DPU Cores_1;Arch of DPU_B4096;RAM Usage_High;Channel Augmentation_Enabled;DepthWiseConv_Enabled;AveragePool_Enabled;Conv ReLU Type_ReLU + LeakyReLU + ReLU6;Number of SFM cores_0;S-AXI Clock Mode_Common with M-AXI Clock;dpu_2x Clock Gating_Disabled;DSP48 Maximal Cascade Length_4;DSP48 Usage_High;Ultra-RAM Use per DPU_0;Enable timestamp auto-update_Enabled;Target Version_1.4.1;AXI Protocol_AXI4;S-AXI Data Width_32;M-AXI GP Data Width_32;M-AXI HP Data Width (DPU)_128;M-AXI HP Data Width (SFM)_128;M-AXI ID Width_2;DSP Slice Count_774;Ultra-RAM Count_0.0;Block-RAM Count_315.0,DPU1_GP_ID_BW=2,DPU1_HP0_ID_BW=2,DPU1_HP1_ID_BW=2,DPU1_HP2_ID_BW=2,DPU1_HP3_ID_BW=2,DPU1_UBANK_IMG_N=0,DPU1_UBANK_WGT_N=0,DPU1_UBANK_BIAS=0,DPU1_DBANK_IMG_N=0,DPU1_DBANK_WGT_N=0,DPU1_DBANK_BIAS=0,DPU2_GP_ID_BW=2,DPU2_HP0_ID_BW=2,DPU2_HP1_ID_BW=2,DPU2_HP2_ID_BW=2,DPU2_HP3_ID_BW=2,DPU2_UBANK_IMG_N=0,DPU2_UBANK_WGT_N=0,DPU2_UBANK_BIAS=0,DPU2_DBANK_IMG_N=0,DPU2_DBANK_WGT_N=0,DPU2_DBANK_BIAS=0,DPU3_GP_ID_BW=2,DPU3_HP0_ID_BW=2,DPU3_HP1_ID_BW=2,DPU3_HP2_ID_BW=2,DPU3_HP3_ID_BW=2,DPU3_UBANK_IMG_N=0,DPU3_UBANK_WGT_N=0,DPU3_UBANK_BIAS=0,DPU3_DBANK_IMG_N=0,DPU3_DBANK_WGT_N=0,DPU3_DBANK_BIAS=0,SFM_ENA=0,SFM_HP0_ID_BW=2,SFM_HP_DATA_BW=128}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "package_project";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "dpu_2x_clk,dpu_2x_resetn,m_axi_dpu_aclk,m_axi_dpu_aresetn,dpu0_interrupt,s_axi_awid[15:0],s_axi_awaddr[31:0],s_axi_awlen[7:0],s_axi_awsize[2:0],s_axi_awburst[1:0],s_axi_awlock[1:0],s_axi_awcache[3:0],s_axi_awprot[2:0],s_axi_awqos[3:0],s_axi_awregion[3:0],s_axi_awuser[15:0],s_axi_awvalid,s_axi_awready,s_axi_wid[15:0],s_axi_wdata[31:0],s_axi_wstrb[3:0],s_axi_wlast,s_axi_wvalid,s_axi_wready,s_axi_bid[15:0],s_axi_bresp[1:0],s_axi_bvalid,s_axi_bready,s_axi_arid[15:0],s_axi_araddr[31:0],s_axi_arlen[7:0],s_axi_arsize[2:0],s_axi_arburst[1:0],s_axi_arlock[1:0],s_axi_arcache[3:0],s_axi_arprot[2:0],s_axi_arqos[3:0],s_axi_arregion[3:0],s_axi_aruser[15:0],s_axi_arvalid,s_axi_arready,s_axi_rid[15:0],s_axi_rdata[31:0],s_axi_rresp[1:0],s_axi_rlast,s_axi_rvalid,s_axi_rready,dpu0_m_axi_instr_awid[1:0],dpu0_m_axi_instr_awaddr[39:0],dpu0_m_axi_instr_awlen[7:0],dpu0_m_axi_instr_awsize[2:0],dpu0_m_axi_instr_awburst[1:0],dpu0_m_axi_instr_awlock[0:0],dpu0_m_axi_instr_awcache[3:0],dpu0_m_axi_instr_awprot[2:0],dpu0_m_axi_instr_awqos[3:0],dpu0_m_axi_instr_awuser[0:0],dpu0_m_axi_instr_awvalid,dpu0_m_axi_instr_awready,dpu0_m_axi_instr_wid[5:0],dpu0_m_axi_instr_wdata[31:0],dpu0_m_axi_instr_wstrb[3:0],dpu0_m_axi_instr_wlast,dpu0_m_axi_instr_wvalid,dpu0_m_axi_instr_wready,dpu0_m_axi_instr_bid[5:0],dpu0_m_axi_instr_bresp[1:0],dpu0_m_axi_instr_bvalid,dpu0_m_axi_instr_bready,dpu0_m_axi_instr_arid[1:0],dpu0_m_axi_instr_araddr[39:0],dpu0_m_axi_instr_arlen[7:0],dpu0_m_axi_instr_arsize[2:0],dpu0_m_axi_instr_arburst[1:0],dpu0_m_axi_instr_arlock[0:0],dpu0_m_axi_instr_arcache[3:0],dpu0_m_axi_instr_arprot[2:0],dpu0_m_axi_instr_arqos[3:0],dpu0_m_axi_instr_aruser[0:0],dpu0_m_axi_instr_arvalid,dpu0_m_axi_instr_arready,dpu0_m_axi_instr_rid[5:0],dpu0_m_axi_instr_rdata[31:0],dpu0_m_axi_instr_rresp[1:0],dpu0_m_axi_instr_rlast,dpu0_m_axi_instr_rvalid,dpu0_m_axi_instr_rready,dpu0_m_axi_data0_awid[1:0],dpu0_m_axi_data0_awaddr[39:0],dpu0_m_axi_data0_awlen[7:0],dpu0_m_axi_data0_awsize[2:0],dpu0_m_axi_data0_awburst[1:0],dpu0_m_axi_data0_awlock[0:0],dpu0_m_axi_data0_awcache[3:0],dpu0_m_axi_data0_awprot[2:0],dpu0_m_axi_data0_awqos[3:0],dpu0_m_axi_data0_awuser[0:0],dpu0_m_axi_data0_awvalid,dpu0_m_axi_data0_awready,dpu0_m_axi_data0_wid[5:0],dpu0_m_axi_data0_wdata[127:0],dpu0_m_axi_data0_wstrb[15:0],dpu0_m_axi_data0_wlast,dpu0_m_axi_data0_wvalid,dpu0_m_axi_data0_wready,dpu0_m_axi_data0_bid[5:0],dpu0_m_axi_data0_bresp[1:0],dpu0_m_axi_data0_bvalid,dpu0_m_axi_data0_bready,dpu0_m_axi_data0_arid[1:0],dpu0_m_axi_data0_araddr[39:0],dpu0_m_axi_data0_arlen[7:0],dpu0_m_axi_data0_arsize[2:0],dpu0_m_axi_data0_arburst[1:0],dpu0_m_axi_data0_arlock[0:0],dpu0_m_axi_data0_arcache[3:0],dpu0_m_axi_data0_arprot[2:0],dpu0_m_axi_data0_arqos[3:0],dpu0_m_axi_data0_aruser[0:0],dpu0_m_axi_data0_arvalid,dpu0_m_axi_data0_arready,dpu0_m_axi_data0_rid[5:0],dpu0_m_axi_data0_rdata[127:0],dpu0_m_axi_data0_rresp[1:0],dpu0_m_axi_data0_rlast,dpu0_m_axi_data0_rvalid,dpu0_m_axi_data0_rready,dpu0_m_axi_data1_awid[1:0],dpu0_m_axi_data1_awaddr[39:0],dpu0_m_axi_data1_awlen[7:0],dpu0_m_axi_data1_awsize[2:0],dpu0_m_axi_data1_awburst[1:0],dpu0_m_axi_data1_awlock[0:0],dpu0_m_axi_data1_awcache[3:0],dpu0_m_axi_data1_awprot[2:0],dpu0_m_axi_data1_awqos[3:0],dpu0_m_axi_data1_awuser[0:0],dpu0_m_axi_data1_awvalid,dpu0_m_axi_data1_awready,dpu0_m_axi_data1_wid[5:0],dpu0_m_axi_data1_wdata[127:0],dpu0_m_axi_data1_wstrb[15:0],dpu0_m_axi_data1_wlast,dpu0_m_axi_data1_wvalid,dpu0_m_axi_data1_wready,dpu0_m_axi_data1_bid[5:0],dpu0_m_axi_data1_bresp[1:0],dpu0_m_axi_data1_bvalid,dpu0_m_axi_data1_bready,dpu0_m_axi_data1_arid[1:0],dpu0_m_axi_data1_araddr[39:0],dpu0_m_axi_data1_arlen[7:0],dpu0_m_axi_data1_arsize[2:0],dpu0_m_axi_data1_arburst[1:0],dpu0_m_axi_data1_arlock[0:0],dpu0_m_axi_data1_arcache[3:0],dpu0_m_axi_data1_arprot[2:0],dpu0_m_axi_data1_arqos[3:0],dpu0_m_axi_data1_aruser[0:0],dpu0_m_axi_data1_arvalid,dpu0_m_axi_data1_arready,dpu0_m_axi_data1_rid[5:0],dpu0_m_axi_data1_rdata[127:0],dpu0_m_axi_data1_rresp[1:0],dpu0_m_axi_data1_rlast,dpu0_m_axi_data1_rvalid,dpu0_m_axi_data1_rready";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of dpu_2x_clk : signal is "xilinx.com:signal:clock:1.0 dpu_2x_clk CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of dpu_2x_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of dpu_2x_clk : signal is "XIL_INTERFACENAME dpu_2x_clk, ASSOCIATED_CLKEN dpu_2x_clk_ce, ASSOCIATED_RESET dpu_2x_resetn, FREQ_HZ 96968727, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN DDR4_zynq_ultra_ps_e_0_1_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of dpu_2x_resetn : signal is "xilinx.com:signal:reset:1.0 dpu_2x_resetn RST";
  attribute X_INTERFACE_MODE of dpu_2x_resetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of dpu_2x_resetn : signal is "XIL_INTERFACENAME dpu_2x_resetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_dpu_aclk : signal is "xilinx.com:signal:clock:1.0 m_axi_dpu_aclk CLK";
  attribute X_INTERFACE_MODE of m_axi_dpu_aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m_axi_dpu_aclk : signal is "XIL_INTERFACENAME m_axi_dpu_aclk, ASSOCIATED_RESET m_axi_dpu_aresetn, ASSOCIATED_BUSIF DPU0_M_AXI_DATA0:DPU0_M_AXI_DATA1:DPU0_M_AXI_DATA2:DPU0_M_AXI_DATA3:DPU0_M_AXI_INSTR:DPU1_M_AXI_DATA0:DPU1_M_AXI_DATA1:DPU1_M_AXI_DATA2:DPU1_M_AXI_DATA3:DPU1_M_AXI_INSTR:DPU2_M_AXI_DATA0:DPU2_M_AXI_DATA1:DPU2_M_AXI_DATA2:DPU2_M_AXI_DATA3:DPU2_M_AXI_INSTR:DPU3_M_AXI_DATA0:DPU3_M_AXI_DATA1:DPU3_M_AXI_DATA2:DPU3_M_AXI_DATA3:DPU3_M_AXI_INSTR:SFM_M_AXI:S_AXI, FREQ_HZ 96968727, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN DDR4_zynq_ultra_ps_e_0_1_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_dpu_aresetn : signal is "xilinx.com:signal:reset:1.0 m_axi_dpu_aresetn RST";
  attribute X_INTERFACE_MODE of m_axi_dpu_aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m_axi_dpu_aresetn : signal is "XIL_INTERFACENAME m_axi_dpu_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of dpu0_interrupt : signal is "xilinx.com:signal:interrupt:1.0 dpu0_interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of dpu0_interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of dpu0_interrupt : signal is "XIL_INTERFACENAME dpu0_interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of s_axi_awid : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWID";
  attribute X_INTERFACE_MODE of s_axi_awid : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_awid : signal is "XIL_INTERFACENAME S_AXI, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 96968727, ID_WIDTH 16, ADDR_WIDTH 32, AWUSER_WIDTH 16, ARUSER_WIDTH 16, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 8, NUM_WRITE_OUTSTANDING 8, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN DDR4_zynq_ultra_ps_e_0_1_pl_clk0, NUM_READ_THREADS 4, NUM_WRITE_THREADS 4, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWADDR";
  attribute X_INTERFACE_INFO of s_axi_awlen : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWLEN";
  attribute X_INTERFACE_INFO of s_axi_awsize : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWSIZE";
  attribute X_INTERFACE_INFO of s_axi_awburst : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWBURST";
  attribute X_INTERFACE_INFO of s_axi_awlock : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWLOCK";
  attribute X_INTERFACE_INFO of s_axi_awcache : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWCACHE";
  attribute X_INTERFACE_INFO of s_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWPROT";
  attribute X_INTERFACE_INFO of s_axi_awqos : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWQOS";
  attribute X_INTERFACE_INFO of s_axi_awregion : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWREGION";
  attribute X_INTERFACE_INFO of s_axi_awuser : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWUSER";
  attribute X_INTERFACE_INFO of s_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWVALID";
  attribute X_INTERFACE_INFO of s_axi_awready : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWREADY";
  attribute X_INTERFACE_INFO of s_axi_wid : signal is "xilinx.com:interface:aximm:1.0 S_AXI WID";
  attribute X_INTERFACE_INFO of s_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 S_AXI WDATA";
  attribute X_INTERFACE_INFO of s_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 S_AXI WSTRB";
  attribute X_INTERFACE_INFO of s_axi_wlast : signal is "xilinx.com:interface:aximm:1.0 S_AXI WLAST";
  attribute X_INTERFACE_INFO of s_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI WVALID";
  attribute X_INTERFACE_INFO of s_axi_wready : signal is "xilinx.com:interface:aximm:1.0 S_AXI WREADY";
  attribute X_INTERFACE_INFO of s_axi_bid : signal is "xilinx.com:interface:aximm:1.0 S_AXI BID";
  attribute X_INTERFACE_INFO of s_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 S_AXI BRESP";
  attribute X_INTERFACE_INFO of s_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI BVALID";
  attribute X_INTERFACE_INFO of s_axi_bready : signal is "xilinx.com:interface:aximm:1.0 S_AXI BREADY";
  attribute X_INTERFACE_INFO of s_axi_arid : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARID";
  attribute X_INTERFACE_INFO of s_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARADDR";
  attribute X_INTERFACE_INFO of s_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARLEN";
  attribute X_INTERFACE_INFO of s_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARSIZE";
  attribute X_INTERFACE_INFO of s_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARBURST";
  attribute X_INTERFACE_INFO of s_axi_arlock : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARLOCK";
  attribute X_INTERFACE_INFO of s_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARCACHE";
  attribute X_INTERFACE_INFO of s_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARPROT";
  attribute X_INTERFACE_INFO of s_axi_arqos : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARQOS";
  attribute X_INTERFACE_INFO of s_axi_arregion : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARREGION";
  attribute X_INTERFACE_INFO of s_axi_aruser : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARUSER";
  attribute X_INTERFACE_INFO of s_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARVALID";
  attribute X_INTERFACE_INFO of s_axi_arready : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARREADY";
  attribute X_INTERFACE_INFO of s_axi_rid : signal is "xilinx.com:interface:aximm:1.0 S_AXI RID";
  attribute X_INTERFACE_INFO of s_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 S_AXI RDATA";
  attribute X_INTERFACE_INFO of s_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 S_AXI RRESP";
  attribute X_INTERFACE_INFO of s_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 S_AXI RLAST";
  attribute X_INTERFACE_INFO of s_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 S_AXI RVALID";
  attribute X_INTERFACE_INFO of s_axi_rready : signal is "xilinx.com:interface:aximm:1.0 S_AXI RREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWID";
  attribute X_INTERFACE_MODE of dpu0_m_axi_instr_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of dpu0_m_axi_instr_awid : signal is "XIL_INTERFACENAME DPU0_M_AXI_INSTR, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 96968727, ID_WIDTH 2, ADDR_WIDTH 40, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN DDR4_zynq_ultra_ps_e_0_1_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awaddr : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWADDR";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awlen : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWLEN";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awsize : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWSIZE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awburst : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWBURST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awlock : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWLOCK";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awcache : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWCACHE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awprot : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWPROT";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awqos : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWQOS";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awuser : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWUSER";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_awready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR AWREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_wid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR WID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_wdata : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR WDATA";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_wstrb : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR WSTRB";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_wlast : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR WLAST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_wvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR WVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_wready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR WREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_bid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR BID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_bresp : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR BRESP";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_bvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR BVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_bready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR BREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_araddr : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARADDR";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arlen : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARLEN";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arsize : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARSIZE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arburst : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARBURST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arlock : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARLOCK";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arcache : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARCACHE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arprot : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARPROT";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arqos : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARQOS";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_aruser : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARUSER";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_arready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR ARREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_rid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR RID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_rdata : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR RDATA";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_rresp : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR RRESP";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_rlast : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR RLAST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_rvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR RVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_instr_rready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_INSTR RREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWID";
  attribute X_INTERFACE_MODE of dpu0_m_axi_data0_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of dpu0_m_axi_data0_awid : signal is "XIL_INTERFACENAME DPU0_M_AXI_DATA0, DATA_WIDTH 128, PROTOCOL AXI4, FREQ_HZ 96968727, ID_WIDTH 2, ADDR_WIDTH 40, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN DDR4_zynq_ultra_ps_e_0_1_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awaddr : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWADDR";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awlen : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWLEN";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awsize : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWSIZE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awburst : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWBURST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awlock : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWLOCK";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awcache : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWCACHE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awprot : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWPROT";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awqos : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWQOS";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awuser : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWUSER";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_awready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 AWREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_wid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 WID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_wdata : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 WDATA";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_wstrb : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 WSTRB";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_wlast : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 WLAST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_wvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 WVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_wready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 WREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_bid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 BID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_bresp : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 BRESP";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_bvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 BVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_bready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 BREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_araddr : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARADDR";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arlen : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARLEN";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arsize : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARSIZE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arburst : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARBURST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arlock : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARLOCK";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arcache : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARCACHE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arprot : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARPROT";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arqos : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARQOS";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_aruser : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARUSER";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_arready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 ARREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_rid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 RID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_rdata : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 RDATA";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_rresp : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 RRESP";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_rlast : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 RLAST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_rvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 RVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data0_rready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA0 RREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWID";
  attribute X_INTERFACE_MODE of dpu0_m_axi_data1_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of dpu0_m_axi_data1_awid : signal is "XIL_INTERFACENAME DPU0_M_AXI_DATA1, DATA_WIDTH 128, PROTOCOL AXI4, FREQ_HZ 96968727, ID_WIDTH 2, ADDR_WIDTH 40, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN DDR4_zynq_ultra_ps_e_0_1_pl_clk0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awaddr : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWADDR";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awlen : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWLEN";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awsize : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWSIZE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awburst : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWBURST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awlock : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWLOCK";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awcache : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWCACHE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awprot : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWPROT";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awqos : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWQOS";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awuser : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWUSER";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_awready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 AWREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_wid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 WID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_wdata : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 WDATA";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_wstrb : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 WSTRB";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_wlast : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 WLAST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_wvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 WVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_wready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 WREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_bid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 BID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_bresp : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 BRESP";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_bvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 BVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_bready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 BREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_araddr : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARADDR";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arlen : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARLEN";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arsize : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARSIZE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arburst : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARBURST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arlock : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARLOCK";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arcache : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARCACHE";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arprot : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARPROT";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arqos : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARQOS";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_aruser : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARUSER";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_arready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 ARREADY";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_rid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 RID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_rdata : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 RDATA";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_rresp : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 RRESP";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_rlast : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 RLAST";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_rvalid : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 RVALID";
  attribute X_INTERFACE_INFO of dpu0_m_axi_data1_rready : signal is "xilinx.com:interface:aximm:1.0 DPU0_M_AXI_DATA1 RREADY";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "DPUCZDX8G_v4_1_0,Vivado 2024.2.2";
begin
end;
