# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/RGMII_system_ila_TX_0.xci
# IP: The module: 'RGMII_system_ila_TX_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/bd_3378.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3378 || ORIG_REF_NAME==bd_3378} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_0/bd_3378_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3378_ila_lib_0 || ORIG_REF_NAME==bd_3378_ila_lib_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_1/bd_3378_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3378_g_inst_0 || ORIG_REF_NAME==bd_3378_g_inst_0} -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3378_ila_lib_0 || ORIG_REF_NAME==bd_3378_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3378_ila_lib_0 || ORIG_REF_NAME==bd_3378_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_0/bd_3378_ila_lib_0_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/bd_3378_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/RGMII_system_ila_TX_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RGMII_system_ila_TX_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.srcs/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/RGMII_system_ila_TX_0.xci
# IP: The module: 'RGMII_system_ila_TX_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/bd_3378.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3378 || ORIG_REF_NAME==bd_3378} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_0/bd_3378_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3378_ila_lib_0 || ORIG_REF_NAME==bd_3378_ila_lib_0} -quiet] -quiet

# IP: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_1/bd_3378_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3378_g_inst_0 || ORIG_REF_NAME==bd_3378_g_inst_0} -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3378_ila_lib_0 || ORIG_REF_NAME==bd_3378_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3378_ila_lib_0 || ORIG_REF_NAME==bd_3378_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/ip/ip_0/bd_3378_ila_lib_0_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/bd_0/bd_3378_ooc.xdc

# XDC: e:/final_prj/final_prj_pl/final_prj_pl.gen/sources_1/bd/RGMII/ip/RGMII_system_ila_TX_0/RGMII_system_ila_TX_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RGMII_system_ila_TX_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
